name: Build Docker Images and Push to Image Registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: 'latest'
        type: string
      project:
        description: 'Project to build'
        type: choice
        options:
          - llm-mock-server
          - ext-auth-mock-server
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY: ${{ vars.IMAGE_REGISTRY || 'higress-registry.cn-hangzhou.cr.aliyuncs.com' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          make image-buildx PROJECT=${{ github.event.inputs.project }} VERSION=${{ github.event.inputs.version }} REGISTRY=${{ env.IMAGE_REGISTRY }}

      - name: Notify success
        run: echo "Docker image built and pushed successfully for project ${{ github.event.inputs.project }} and version ${{ github.event.inputs.version }}"